"""Init migration

Revision ID: ce028c679c99
Revises: 
Create Date: 2024-12-14 02:41:52.067988

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce028c679c99"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.Column("username", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    sa.UniqueConstraint("user_id", name=op.f("uq_users_user_id")),
    schema="public"
    )
    op.create_table("trips",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("days_needed", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["public.users.user_id"], name=op.f("fk_trips_user_id_users"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    schema="public"
    )
    op.create_index(op.f("ix_public_trips_title"), "trips", ["title"], unique=False, schema="public")
    op.create_table("items",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("user_id", sa.BigInteger(), nullable=False),
    sa.Column("trip_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["trip_id"], ["public.trips.id"], name=op.f("fk_items_trip_id_trips"), ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["public.users.user_id"], name=op.f("fk_items_user_id_users"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    schema="public"
    )
    op.create_index(op.f("ix_public_items_title"), "items", ["title"], unique=False, schema="public")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_items_title"), table_name="items", schema="public")
    op.drop_table("items", schema="public")
    op.drop_index(op.f("ix_public_trips_title"), table_name="trips", schema="public")
    op.drop_table("trips", schema="public")
    op.drop_table("users", schema="public")
    # ### end Alembic commands ###
