global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'consumer'
    static_configs:
      - targets: ['localhost:8010']